//This line declares the package that this class belongs to
package com.last.feign.model;
//These are the import statements for required classes
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

//This class represents an Employee entity in the database
@Entity
@Table(name="Employee")
public class Employee {

	// Employee ID, automatically generated by the database
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long empid;
	
	// Employee name
	@Column(name="emp_name")
	private String emp_name;
	
	// Employee salary
	@Column(name="emp_salary")
	private Float emp_salary;
	
	// Employee age
	@Column(name="emp_age")
	private int emp_age;
	
	// Employee city
	@Column(name="emp_city")
	private String emp_city;
	
	// Getters and setters for the above fields
	// Getter method for Employee ID
	public long getEmpid() {
		return empid;
	}
	// Setter method for Employee ID
	public void setEmpid(long empid) {
		this.empid = empid;
	}
	// Getter method for Employee name
	public String getEmp_name() {
		return emp_name;
	}
	// Setter method for Employee name
	public void setEmp_name(String emp_name) {
		this.emp_name = emp_name;
	}
	// Getter method for Employee salary
	public Float getEmp_salary() {
		return emp_salary;
	}
	// Setter method for Employee salary
	public void setEmp_salary(Float emp_salary) {
		this.emp_salary = emp_salary;
	}
	// Getter method for Employee age
	public int getEmp_age() {
		return emp_age;
	}
	// Setter method for Employee age
	public void setEmp_age(int emp_age) {
		this.emp_age = emp_age;
	}
	// Getter method for Employee city
	public String getEmp_city() {
		return emp_city;
	}
	// Setter method for Employee city
	public void setEmp_city(String emp_city) {
		this.emp_city = emp_city;
	}
	
	// Constructors for the class
	// Constructor with all fields
	public Employee(long empid, String emp_name, Float emp_salary, int emp_age, String emp_city) {
		super();
		this.empid = empid;
		this.emp_name = emp_name;
		this.emp_salary = emp_salary;
		this.emp_age = emp_age;
		this.emp_city = emp_city;
	}
	// Default constructor
	public Employee() {
		
	}
	
	// toString method to convert object to string representation
	@Override
	public String toString() {
		return "Employee [empid=" + empid + ", emp_name=" + emp_name + ", emp_salary=" + emp_salary + ", emp_age="
				+ emp_age + ", emp_city=" + emp_city + "]";
	}
}
